name: Varun & Ishani

on:
  push:
    branches:
      - main

jobs:
  firstjob:
    name: varun
    runs-on: ubuntu-latest
    steps:
      - name: Varun
        run: echo "my name is varun"

  Secondjob:
    name: Ishani
    runs-on: ubuntu-latest
    needs: firstjob
    steps:
      - name: Ishani
        run: echo "my name is Ishani Singh"
